//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackDown.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cli-tools.json")]
        public string CLI_TOOLS_FILE {
            get {
                return ((string)(this["CLI_TOOLS_FILE"]));
            }
            set {
                this["CLI_TOOLS_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$cel")]
        public string TARGET_PLACEHOLDER {
            get {
                return ((string)(this["TARGET_PLACEHOLDER"]));
            }
            set {
                this["TARGET_PLACEHOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$forras")]
        public string SOURCE_PLACEHOLDER {
            get {
                return ((string)(this["SOURCE_PLACEHOLDER"]));
            }
            set {
                this["SOURCE_PLACEHOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("backup-settings.json")]
        public string BACKUP_SETTINGS_FILE {
            get {
                return ((string)(this["BACKUP_SETTINGS_FILE"]));
            }
            set {
                this["BACKUP_SETTINGS_FILE"] = value;
            }
        }
    }
}
